[package]
name = "doc_parser_utils"
version = "0.1.0"
authors = ["philippeitis <33013301+philippeitis@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "doc_parser_utils"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.14.2"
features = ["extension-module"]