version: "3.9"
services:
  specifier_nlp:
    image: specifier_nlp:latest
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - "nlp_specifier_cache:/server/cache/"
    network_mode: "host"
volumes:
    nlp_specifier_cache:
        external: false